# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Mon Nov  4 11:24:06 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.Qwt5 import QwtPlot

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1002, 685)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pv = QtGui.QLCDNumber(self.centralwidget)
        self.pv.setGeometry(QtCore.QRect(886, 130, 61, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pv.setFont(font)
        self.pv.setFrameShape(QtGui.QFrame.Panel)
        self.pv.setFrameShadow(QtGui.QFrame.Plain)
        self.pv.setNumDigits(4)
        self.pv.setDigitCount(4)
        self.pv.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.pv.setObjectName(_fromUtf8("pv"))
        self.sp = QtGui.QSpinBox(self.centralwidget)
        self.sp.setGeometry(QtCore.QRect(120, 129, 63, 31))
        self.sp.setMinimum(100)
        self.sp.setMaximum(900)
        self.sp.setProperty("value", 512)
        self.sp.setObjectName(_fromUtf8("sp"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 260, 121, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.Ts = QtGui.QSpinBox(self.layoutWidget)
        self.Ts.setMinimum(10)
        self.Ts.setMaximum(50)
        self.Ts.setProperty("value", 15)
        self.Ts.setObjectName(_fromUtf8("Ts"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.Ts)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_4)
        self.Kp = QtGui.QDoubleSpinBox(self.centralwidget)
        self.Kp.setGeometry(QtCore.QRect(447, 63, 71, 31))
        self.Kp.setAutoFillBackground(False)
        self.Kp.setMaximum(999.9)
        self.Kp.setSingleStep(0.1)
        self.Kp.setProperty("value", 1.0)
        self.Kp.setObjectName(_fromUtf8("Kp"))
        self.Kd = QtGui.QDoubleSpinBox(self.centralwidget)
        self.Kd.setGeometry(QtCore.QRect(428, 239, 71, 31))
        self.Kd.setMaximum(999.9)
        self.Kd.setSingleStep(0.1)
        self.Kd.setObjectName(_fromUtf8("Kd"))
        self.Ki = QtGui.QDoubleSpinBox(self.centralwidget)
        self.Ki.setGeometry(QtCore.QRect(428, 150, 71, 31))
        self.Ki.setMaximum(999.9)
        self.Ki.setSingleStep(0.1)
        self.Ki.setObjectName(_fromUtf8("Ki"))
        self.pid_off = QtGui.QLabel(self.centralwidget)
        self.pid_off.setEnabled(True)
        self.pid_off.setGeometry(QtCore.QRect(61, 43, 911, 301))
        font = QtGui.QFont()
        font.setKerning(True)
        self.pid_off.setFont(font)
        self.pid_off.setText(_fromUtf8(""))
        self.pid_off.setPixmap(QtGui.QPixmap(_fromUtf8("pid_off.png")))
        self.pid_off.setScaledContents(True)
        self.pid_off.setObjectName(_fromUtf8("pid_off"))
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 370, 971, 281))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.plot = QwtPlot(self.layoutWidget1)
        self.plot.setObjectName(_fromUtf8("plot"))
        self.horizontalLayout.addWidget(self.plot)
        self.plot_e = QwtPlot(self.layoutWidget1)
        self.plot_e.setObjectName(_fromUtf8("plot_e"))
        self.horizontalLayout.addWidget(self.plot_e)
        self.e = QtGui.QLCDNumber(self.centralwidget)
        self.e.setGeometry(QtCore.QRect(266, 130, 61, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.e.setFont(font)
        self.e.setFrameShape(QtGui.QFrame.Panel)
        self.e.setFrameShadow(QtGui.QFrame.Plain)
        self.e.setNumDigits(5)
        self.e.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.e.setObjectName(_fromUtf8("e"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(850, 10, 141, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.pid_on = QtGui.QLabel(self.centralwidget)
        self.pid_on.setEnabled(True)
        self.pid_on.setGeometry(QtCore.QRect(61, 43, 911, 301))
        font = QtGui.QFont()
        font.setKerning(True)
        self.pid_on.setFont(font)
        self.pid_on.setText(_fromUtf8(""))
        self.pid_on.setPixmap(QtGui.QPixmap(_fromUtf8("pid_on.png")))
        self.pid_on.setScaledContents(True)
        self.pid_on.setObjectName(_fromUtf8("pid_on"))
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 178, 33))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget2)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.boton_pid_on = QtGui.QPushButton(self.layoutWidget2)
        self.boton_pid_on.setObjectName(_fromUtf8("boton_pid_on"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.boton_pid_on)
        self.boton_pid_off = QtGui.QPushButton(self.layoutWidget2)
        self.boton_pid_off.setEnabled(False)
        self.boton_pid_off.setObjectName(_fromUtf8("boton_pid_off"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.boton_pid_off)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.boton_pid_on, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.on)
        QtCore.QObject.connect(self.boton_pid_off, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.off)
        QtCore.QObject.connect(self.Ts, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.set_param)
        QtCore.QObject.connect(self.Ki, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.set_param)
        QtCore.QObject.connect(self.Kp, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.set_param)
        QtCore.QObject.connect(self.Kd, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.set_param)
        QtCore.QObject.connect(self.sp, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.set_param)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Control PID con Arduino", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Ts [ms]", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#0000ff;\">CITEDEF - DVA</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.boton_pid_on.setText(QtGui.QApplication.translate("MainWindow", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.boton_pid_off.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))

